### ISSUE TITLE
Uncaught TypeError: tab.item.getTitle is not a function

### ISSUE THREAD

**Issue by bpazar** [iyonaga/minimap-lens#26]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Education
**Thrown From**: [minimap-lens](https://github.com/iyonaga/minimap-lens) package 0.7.0

### Stack Trace

Uncaught TypeError: tab.item.getTitle is not a function

```
At C:\Users\bella\AppData\Local\atom\app-1.47.0\resources\app.asar\node_modules\tabs\lib\tab-view.js:310

TypeError: tab.item.getTitle is not a function
    at TabView.module.exports.TabView.updateTitle (/app.asar/node_modules/tabs/lib/tab-view.js:310:26)
    at /app.asar/node_modules/tabs/lib/tab-view.js:37:12)
    at TabBarView.module.exports.TabBarView.addTabForItem (/app.asar/node_modules/tabs/lib/tab-bar-view.js:226:17)
    at /app.asar/node_modules/tabs/lib/tab-bar-view.js:161:24
    at Function.simpleDispatch (/app.asar/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/app.asar/node_modules/event-kit/dist/emitter.js:257:28)
    at Pane.addItem (/app.asar/src/pane.js:685:18)
    at MinimapLens.prepareCreateLens (/packages/minimap-lens/lib/minimap-lens.js:256:10)
    at MinimapLens.showLens (/packages/minimap-lens/lib/minimap-lens.js:178:29)
    at MinimapLens.onMouseEnter (/packages/minimap-lens/lib/minimap-lens.js:116:12)
```

### Commands

```
     -9:09.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
highlight-selected 0.17.0 
kite 0.185.0 
language-latex 1.2.0 
latex 0.50.2 
minimap 4.29.9 
minimap-lens 0.7.0 
pdf-view 0.72.0 
script 3.26.0 
```

**Comment by aminya** [comment]
Could you explain when this happens?
