### ISSUE TITLE
Uncaught TypeError: Cannot read property 'minimap-autohide' of undefined

### ISSUE THREAD

**Issue by WZDafunk** [iyonaga/minimap-lens#36]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.7
**Thrown From**: [minimap-lens](https://github.com/iyonaga/minimap-lens) package 0.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'minimap-autohide' of undefined

```
At /Users/braulio.delatorre/.atom/packages/minimap-lens/lib/minimap-lens.js:294

TypeError: Cannot read property 'minimap-autohide' of undefined
    at MinimapLens.calcEditorDims (/packages/minimap-lens/lib/minimap-lens.js:294:28)
    at MinimapLens.showLens (/packages/minimap-lens/lib/minimap-lens.js:217:46)
    at /packages/minimap-lens/lib/minimap-lens.js:135:14
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-live-server 2.3.0 
auto-update-packages 1.0.1 
browser-plus 0.0.98 
busy-signal 2.0.1 
expose 0.15.0 
file-icons 2.1.46 
highlight-selected 0.17.0 
intentions 1.1.5 
linter 3.1.1 
linter-ui-default 2.3.5 
minimap 4.36.6 
minimap-cursorline 1.0.1 
minimap-find-and-replace 5.0.7 
minimap-git-diff 4.3.5 
minimap-highlight-selected 4.6.4 
minimap-lens 0.8.1 
minimap-linter 2.2.2 
minimap-pigments 0.2.2 
pigments 0.40.6 
platformio-ide-terminal 2.10.1 
remote-ftp 2.2.4 
restart-atom 0.2.0 
todo-show 2.3.2 
```

**Comment by iyonaga** [comment]
@WZDafunk
Sorry for the late response.
I fixed this issue in version 0.8.2.
